#!/usr/bin/env python
# encoding: utf-8
# Copyright (c) 2012 SjB <steve@sagacity.ca>. All Rights Reserved.

# Get Global variable from root wscript file
# from waflib import Context
# APPNAME = getattr(Context.g_module, 'APPNAME')

# Reference external Assembly
# bld.read_assembly('Eto')

# building a cs application
bld(features = 'cs',
	source = ['test-app.cs'],
#	copy_dependent_files = False,
#	resources = ['./resources/app_icon.png,app_icon.png'],
	bintype = 'exe', # use 'winexe' for ui application
	install_path = '${PREFIX}/lib/${APPNAME}',
	gen = '%s.exe' % bld.env.APPNAME,
	use = 'test-lib')
