#!/usr/bin/env python
# encoding: utf-8
# Copyright (c) 2012 SjB <steve@sagacity.ca>. All Rights Reserved.

# Get Global variable from root wscript file
# from waflib import Context
# APPNAME = getattr(Context.g_module, 'APPNAME')

# Reference external Assembly
bld.read_assembly('AudiologyWidgets', install_path='${PREFIX}/lib/${APPNAME}')
bld.read_assembly('Eto', install_path='${PREFIX}/lib/${APPNAME}')
bld.read_assembly('Eto.Platform', install_path='${PREFIX}/lib/${APPNAME}')

# building a cs application
tg = bld(features = 'cs cs_dev',
		source = ['test-app.cs'],
	#	resources = ['./resources/app_icon.png,app_icon.png'],
		bintype = 'exe', # use 'winexe' for ui application
		install_path = '${PREFIX}/lib/${APPNAME}',
		gen = '%s.exe' % bld.env.APPNAME,
		use = 'test-lib Eto Eto.Platform')
